# config.yml: Collects the information about the repository and the author.
---
# Project Information
repo_owner: jekwwer
repo_name: markdown-docs-kit
project_name: Markdown Docs Kit

# School Project Information
school_name: Placeholder University
course_name: Placeholder Course
academic_year: 2024-2025

# Contact Information
contact_email: evgenii.shiliaev@jekwwer.com
report_email: report@jekwwer.com

# External Links
contributing_url: https://github.com/jekwwer/markdown-docs-kit/blob/main/CONTRIBUTING.md
documentation_url: https://jekwwer.com/markdown-docs-kit
discussions_url: https://github.com/jekwwer/markdown-docs-kit/discussions
issues_url: https://github.com/jekwwer/markdown-docs-kit/issues
security_url: https://github.com/jekwwer/markdown-docs-kit/security/advisories

# Security Information
response_time: 48
resolution_time: 7
latest_version: no_value
previous_version: no_value
